### ISSUE TITLE
Setup CI + codestyle tools

### ISSUE THREAD

**Issue by nsidnev** [dmgolembiowski/edgemorph#7]
While working on #6, I ran into several issues and to solve them I want to suggest the following:
1. Set up GitHub Actions for all parts of this project (Rust framework, Python framework, EDM CLI) to check if all PRs and branches are in the correct state.
2. Add autoformatters (now) + linters (after a while) that will handle common errors (for example, extra spaces after lines).

Here are the checklists:

Python:
- [ ] Setup black for the Python code style.
- [ ] Setup isort for correct imports order.
- [ ] Setup autoflake to remove all unused variables and imports.
- [ ] Setup flake8 to handle common errors. Maybe extend it with wemake-python-styleguide (optional).
- [ ] Setup GitHub Actions for tests and style checking.

Rust:
- [ ] Setup Clippy to handle common errors.
- [ ] Setup GitHub Actions for tests and style checking (at least using `rustfmt`).

This isn't a complete or required list, but these are the tools I've been using for a long time, and they help me maintain a good codebase in my personal and work projects.

@dmgolembiowski. What do you think about this?

**Comment by dmgolembiowski** [comment]
Yes, agreed. EDM-cli has some of the messiest code I've written. (The Rust rewrite will be much cleaner, I promise.) We should definitely add some linting and code hygiene tools in the meantime.

**Comment by dmgolembiowski** [comment]
> Python:
> 
> * [ ]  Setup black for the Python code style.
> * [ ]  Setup isort for correct imports order.

`isort` may not be the best choice here since `edb` cannot be imported using best practices since it does not have a convenient `edb` namespace. (See https://github.com/edgedb/edgedb/blob/master/edb/__init__.py). It's not ideal but until there's a valid way to import the parser and serializer, the current setup is the only way I can get the packages to be imported. 
Alternatively, there may be something we can do using `importlib` to bring in a wheel from a hyperlink.

**Comment by nsidnev** [comment]
Check #8 please. I think I wrote a suitable solution that will handle this case (also added a separate CI for the Python EDM version and fixed some linter issues).

**Comment by dmgolembiowski** [comment]
I would like to revisit CI for this project. After some opportunities to tinker with Github actions in other repositories, I have a better idea of what is needed. 

"To Do" items:
- Refine the setup.py and pyproject.toml inclusions to be more amendable to PyPi package submissions. Poetry makes certain things "possible", but at the same time is tricky to integrate with EdgeDB's setup/build process. 
- Finish the testing harness integration so that unit and integration tests can be automated. I didn't do a good job setting up the tests, and this needs to be fixed.

**Comment by dmgolembiowski** [comment]
Closing in favor of issue #15
